### PR TITLE
Xp/fix pixel size

### PR DESCRIPTION
**Pull request by gregllong**
Sorry the pull request should happen here. 

@aransfor @jayich please review

@aransfor I'm sorry that I removed some functionalities that I thought are nice but I really don't have time to get them all working. We can add them back later if we have time.

The beam profiler seems to work and output beam sizes that agree with knife edge measurements.

Also now we have the ability to choose which color pixel to use (red, green or blue. presumably for 780nm we should use red, and for 399nm we should use blue).

### CODE REVIEW

**Comment by aransfor** [comment]
Theres so many changes here... I either need a lot of time to go through them or we can just use this as a different version. I think changes like "changed scaling" should be smaller pull requests in the future

**Comment by jayich** [comment]
Perhaps we should make a branch "simple" for this version?  The user could choose between master and simple.

**Comment by jayich** [comment]
@gregllong , bump.

**Comment by jayich** [comment]
@gregllong , bump.  Come up with a new high level branch name for this.  xp_simple.  simple_profile might be good.

**Comment by gregllong** [comment]
@jayich @aransfor See [this pull request](https://github.com/CampbellGroup/PiBeamProfiler/pull/4)

**Pull request closed without merging**
