### PR TITLE
Physics changes tabs spaces and more

### PR DESCRIPTION
**Pull request by jayich**
Review: @aransfor , @gregllong

Fixing mixed tabs and spaces to just tabs was an important commit, https://github.com/aransfor/PiBeamProfiler/commit/f1175dcc535204758f07b6581d71020d491cb1cb.  The other important commit was explicitly displaying the measured value, https://github.com/aransfor/PiBeamProfiler/commit/21e0d5dcfbc2dc51f9723a20885c83eb03bab27b.

Other changes include pep8 and general tidying.

### CODE REVIEW

**Comment by gregllong** [comment]
LGTM

**Comment by gregllong** [comment]
I just double checked the math on the 1/e^2 beam diameter. Looks good.

**Comment by aransfor** [comment]
other than the pix_to_um LGTM

**Comment by gregllong** [comment]
Just to clarify: this variable converts number of pixels to um. And since 1 pixel = 5.865 um for 640*480 resolution, its value is 5.865. Does that sound right? If it is I think the name pix_to_um is more appropriate.

**Comment by jayich** [comment]
Review: @aransfor, @gregllong , please take a look at commit https://github.com/CampbellGroup/PiBeamProfiler/commit/67d85ae2448af293d40acb284cdd051fa13f271e

where I tried to make it very clear what is happening with the conversion from camera resolution scaled pixels to micrometers.

**Comment by aransfor** [comment]
this looks good to merger

**Comment by jayich** [comment]
Before merging we checked that this worked with the hardware.  There are still calibration issues.

**Pull request merged**
